version: 2.1

orbs: 
  go: circleci/go@1.7.1
  

run:
when: "branch =~ '.*' OR pull_request =~'.*'"  
jobs:
  manylinux2014-aarch64:
    parameters:
      cibw_build:
        type: string
        default: "cp37-*"
    

    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run:  test -z "$(git status --porcelain)" || (echo "please run 'make -C examples/kubernetes/connectivity-check fmt all' and submit your changes"; exit 1)
      
      - run:  sudo ip -6 route add 2001:db8:1::/64 dev docker0
      - run:  sudo sysctl net.ipv6.conf.default.forwarding=1
      - run:  sudo sysctl net.ipv6.conf.all.forwarding=1
      - run:  sudo systemctl restart docker
     
      - run:  sudo apt-get install apt-transport-https --yes && \
      - run:  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | tee /etc/apt/sources.list.d/helm-stable-debian.list && \
      - run:  sudo apt-get update && \
      - run:  sudo apt-get install helm && \
      - run:  helm upgrade -i cilium ./install/kubernetes/cilium \
      - run:  --namespace kube-system \
      - run:  --set nodeinit.enabled=true \
      - run:  --set kubeProxyReplacement=strict \
      - run:  --set ipam.mode=kubernetes \
      - run:  --set image.repository=quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/cilium-ci \
      - run:  --set image.tag=${{ steps.vars.outputs.tag }} \
      - run:  --set image.pullPolicy=IfNotPresent \
      - run:  --set image.useDigest=false \
      - run:  --set hubble.relay.enabled=true \
      - run:  --set hubble.relay.image.repository=quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/hubble-relay-ci \
      - run:  --set hubble.relay.image.tag=${{ steps.vars.outputs.tag }} \
      - run:  --set hubble.relay.image.pullPolicy=IfNotPresent \
      - run:  --set hubble.relay.image.useDigest=false \
      - run:  --set operator.image.repository=quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/operator \
      - run:  --set operator.image.suffix=-ci \
      - run:  --set operator.image.tag=${{ steps.vars.outputs.tag }} \
      - run:  --set operator.image.pullPolicy=IfNotPresent \
      - run:  --set operator.image.useDigest=false \
      - run:  --set ipv6.enabled=true \
      - run:  --set ipv4.enabled=false \
      - run:  --set tunnel=disabled \
      - run:  --set autoDirectNodeRoutes=true \
      - run:  --set ipv6NativeRoutingCIDR=2001:db8:1::/64 \
      - run:  --set ingressController.enabled=true
      - run:  kubectl wait -n kube-system --for=condition=Ready --all pod --timeout=${{ env.TIMEOUT }}
      - run:  kubectl wait --for condition=Established crd/ciliumnetworkpolicies.cilium.io --timeout=5m
      - run:  kubectl port-forward -n kube-system deployment/hubble-relay 4245:4245 &
      - run:  kubectl apply -f ${{ env.CONFORMANCE_TEMPLATE }}
      - run:  kubectl wait --for=condition=Available --all deployment --timeout=${{ env.TIMEOUT }}
      
workflows:
  version: 2.1
  main:
    jobs:
      - manylinux2014-aarch64:
          matrix:
            parameters:
              cibw_build:
                - "cp37*"
